general:
  # Debug mode, only for development. Is overwritten by ${SEARXNG_DEBUG}
  debug: false
  # displayed name
  instance_name: "CodeExplainerSearch"
  # For example: https://example.com/privacy
  privacypolicy_url: false
  # use true to use your own donation page written in searx/info/en/donate.md
  # use false to disable the donation link
  donation_url: false
  # mailto:contact@example.com
  contact_url: false
  # record stats
  enable_metrics: true
  # expose stats in open metrics format at /metrics
  # leave empty to disable (no password set)
  # open_metrics: <password>
  open_metrics: ''

brand:
  new_issue_url: https://github.com/searxng/searxng/issues/new
  docs_url: https://docs.searxng.org/
  public_instances: https://searx.space
  wiki_url: https://github.com/searxng/searxng/wiki
  issue_url: https://github.com/searxng/searxng/issues

search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 0
  # Existing autocomplete backends: "360search", "baidu", "brave", ...
  autocomplete: ""
  # minimum characters to type before autocompleter starts
  autocomplete_min: 4
  # backend for the favicon near URL in search results
  favicon_resolver: ""
  # Default search language, leave blank to detect from browser
  default_lang: "auto"
  # max_page: 0  # if paging supported, 0 means unlimited
  # ban time in seconds after engine errors
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    # Access denied or HTTP 402/403
    SearxEngineAccessDenied: 86400
    # CAPTCHA
    SearxEngineCaptcha: 86400
    # Too many requests / HTTP 429
    SearxEngineTooManyRequests: 3600
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    recaptcha_SearxEngineCaptcha: 604800

  # remove format to deny access, use lower case.
  formats:
    - html

server:
  # Overwritten by ${SEARXNG_PORT} and ${SEARXNG_BIND_ADDRESS}
  port: 8888
  bind_address: "127.0.0.1"
  # public_instance flags
  limiter: false
  public_instance: false
  secret_key: "1d634d18a35ac14959f0612e2b8fc606253c5242860f6c4f36a0507977e35df0"
  image_proxy: false
  http_protocol_version: "1.0"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

redis:
  url: false

ui:
  static_path: ""
  static_use_hash: false
  templates_path: ""
  query_in_title: false
  infinite_scroll: false
  default_theme: simple
  center_alignment: false
  default_locale: ""
  results_on_new_tab: false
  theme_args:
    simple_style: auto
  search_on_category_select: true
  hotkeys: default
  url_formatting: pretty

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: true
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: false
  searx.plugins.tor_check.SXNGPlugin:
    active: false
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: false

# Further engine definitions, scheduling, hostnames, etc., follow in the same file…
